name: Backend Pipeline

on:
  workflow_dispatch:
  push:
    branches:
    - main
    paths:
    - 'dvn-workshop-apps/backend/**'

permissions:
  id-token: write
  
env:
    BACKEND_REPOSITORY: dvn-workshop/production/backend
    IMAGE_TAG: ${{ github.sha }}

jobs:
  backend:
    name: Backend Continuous Deployment
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4.2.1
      with:
        aws-region: ${{ vars.AWS_REGION }}
        role-to-assume: ${{ vars.AWS_ROLE_ARN }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build, tag, and push docker image to Amazon ECR
      env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
      run: |
          docker build -f ./dvn-workshop-apps/backend/YoutubeLiveApp/Dockerfile -t $REGISTRY/$BACKEND_REPOSITORY:$IMAGE_TAG ./dvn-workshop-apps/backend/YoutubeLiveApp
          docker push $REGISTRY/$BACKEND_REPOSITORY:$IMAGE_TAG

    - uses: actions/checkout@v4
      with:
        repository: lucasnbrasileiro/gitops
        token: ${{ secrets.PAT }}

    - name: Kustomize Edit Image
      env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
      run: |
          kustomize edit set image $REGISTRY/$BACKEND_REPOSITORY=$REGISTRY/$BACKEND_REPOSITORY:$IMAGE_TAG
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add ./kustomization.yml
          git commit -m "[BOT] Changed backend image to $REGISTRY/$BACKEND_REPOSITORY:$IMAGE_TAG"
          git push
